SELECT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) AS SALES FROM PRODUCT INNER JOIN OFFLINE_SALE
ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SUM(PRICE*SALES_AMOUNT) DESC, PRODUCT_CODE;