SELECT CONCAT('/home/grep/src/',USED_GOODS_BOARD.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS STR FROM USED_GOODS_BOARD
INNER JOIN USED_GOODS_FILE
ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_FILE.BOARD_ID
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY STR DESC;